## NUMPY


In [ ]:
#numpy -- numerical python
# linear algebra
# it is used to perform operations on arrays,
# it is used to perform operations on matrices,
# it is used to perform operations on vectors,

#array vs list
# array is faster than list
# array is more memory efficient than list
#array store same type of data elements
#  arry are denoted by [] (square )
#pip install numpy --> cmd --> to install numpy

In [ ]:
#array 
#1d --> you can say its just a list 
#2d --> list of lists-->matrices-->row and column --> mxn
#3d --> array of 2d array

In [1]:
import numpy as np 

In [4]:
#how to create array 
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr2 = np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr3 = np.ones(5)
arr3 = np.zeros(5)
arr3

array([0., 0., 0., 0., 0.])

In [9]:
arr4 = np.linspace(0,10,50)
arr4

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [10]:
##2d array 
arr5 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr7 = np.arange(30).reshape(5,6)
arr7.dtype
arr7.size
arr7.shape
# arr7.ndim

(5, 6)

In [18]:
arr7.T.shape

(6, 5)

In [13]:
arr3 = np.ones((2,3))
# arr3 = np.zeros(5)
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#to convert multidimensional array into 1d array
arr8 = arr7.ravel()
arr8 = arr7.flatten()
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
arr7 = np.random.random(10)
arr7 = np.random.randint(0,10,10)
arr7 = np.random.randint(0,10,(3,3))
arr7

array([[7, 0, 0],
       [3, 9, 2],
       [0, 2, 6]], dtype=int32)

In [24]:
#3d array -->(table,row,col)
arr9 = np.arange(27).reshape(3,3,3)
arr9

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [27]:
arr7 = np.arange(30).reshape(5,6)
np.max(arr7)
np.min(arr7)
np.sum(arr7)
np.mean(arr7)
np.median(arr7)
np.var(arr7)
np.std(arr7)

np.float64(8.65544144839919)